<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.encoder_factory.generic' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/PasswordEncoderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/BasePasswordEncoder.php';
include_once $this->targetDirs[3].'/src/Security/PasswordEncoder.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/EncoderFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/EncoderFactory.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/SelfSaltingEncoderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/BCryptPasswordEncoder.php';

return $this->privates['security.encoder_factory.generic'] = new \Symfony\Component\Security\Core\Encoder\EncoderFactory(array('Symfony\\Component\\Security\\Core\\User\\User' => new \App\Security\PasswordEncoder(($this->services['Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder'] ?? $this->services['Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder'] = new \Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder(13)))));
