<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWG1stSG\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWG1stSG/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWG1stSG.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerWG1stSG\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerWG1stSG\srcProdProjectContainer(array(
    'container.build_hash' => 'WG1stSG',
    'container.build_id' => '9e3a1bfa',
    'container.build_time' => 1524603968,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWG1stSG');
