<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/PasswordEncoderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/BasePasswordEncoder.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/SelfSaltingEncoderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/BCryptPasswordEncoder.php';

return $this->services['Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder'] = new \Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder(13);
