<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5nvGZR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5nvGZR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerY5nvGZR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerY5nvGZR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerY5nvGZR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Y5nvGZR',
    'container.build_id' => '8c062bd4',
    'container.build_time' => 1524605913,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5nvGZR');
