<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKsbe8IB\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKsbe8IB/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKsbe8IB.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKsbe8IB\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKsbe8IB\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ksbe8IB',
    'container.build_id' => '12d19ae7',
    'container.build_time' => 1524609908,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKsbe8IB');
