<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUUoJ4QV\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUUoJ4QV/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUUoJ4QV.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUUoJ4QV\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUUoJ4QV\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UUoJ4QV',
    'container.build_id' => 'd79893a4',
    'container.build_time' => 1524609695,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUUoJ4QV');
